### ISSUE TITLE
Jetpack activation error

### ISSUE THREAD

**Issue by pjbeyer** [xyu/heroku-wp#76]
When trying to connect Jetpack to a WordPress.com account, an error is produced in the Heroku logs and Jetpack complains the _site is inaccessible or returned an error: transport error - HTTP status code was not 200 (502) [-32300]_. The error log shows:
`2016-12-23T15:43:39.349647+00:00 app[web.1]: 2016/12/23 15:43:39 [error] 134#0: *93 upstream sent too big header while reading response header from upstream, client: 192.0.87.146, server: localhost, request: "POST /xmlrpc.php?for=jetpack HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.13937.sock:", host: "pjb-heroku-wp.herokuapp.com", referrer: "https://pjb-heroku-wp.herokuapp.com/xmlrpc.php?for=jetpack"`

I've reproduced this by cloning the repository, initializing a new Heroku app, activating Jetpack, and then connecting to WordPress.com.

**Comment by pjbeyer** [comment]
Modifying the Nginx proxy buffer settings eliminates the above error but simultaneously introduces a new one.

I added the following to the _support/nginx.inc.conf_ file:
`proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;`

The error log shows:
`...[error] 125#0: *12 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.0.87.146, server: localhost, request: "POST /xmlrpc.php?for=jetpack&token=l%5EzPuIvuDWf%25%5EUnVm65Nsgx%26u82qa%29tT%3A1%3A0&timestamp=1482527583&nonce=uinHML6GwN&body-hash=lrmKnCA6pjrU%2FJugP4U8pWyAZQI%3D&signature=rjpA4i0KPDWQaV52ndMMQ2rtgWQ%3D HTTP/1.1", upstream: "fastcgi://unix:/tmp/heroku.fcgi.13937.sock:", host: "pjb-heroku-wp.herokuapp.com", referrer: "https://pjb-heroku-wp.herokuapp.com/xmlrpc.php?...`

**Comment by pjbeyer** [comment]
It turns out the only change necessary to address this issue was to revert to PHP 7.0.x (from 7.1.x). In my testing, the Nginx proxy buffer settings did not need to be modified. Jetpack is activated and working properly for me now.

**Comment by xyu** [comment]
Fixed by #75, thanks for the PR!

**Comment by pjbeyer** [comment]
Thanks @xyu !

**Comment by toddheslin** [comment]
I have the latest release of this repo and I'm still receiving this same error. My heroku install log shows:

```
remote: -----> Installing platform packages...
remote:        - php (7.0.15)
remote:        - ext-gd (bundled with php)
remote:        - apache (2.4.20)
remote:        - nginx (1.8.1)
remote: -----> Installing dependencies...
remote:        Composer version 1.2.4 2016-12-06 22:00:51
remote:        Loading composer repositories with package information
remote:        Installing dependencies from lock file
remote:          - Installing composer/installers (v1.2.0)
remote:            Loading from cache
remote:
remote:          - Installing wordpress/wordpress (4.7.2)
remote:            Loading from cache
```
